services:
  app:
    build: .
    image: todolist-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://admin:admin@db:5432/nestdb?schema=nestdb
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: nestdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d nestdb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
# volumes:
#   pgdata:
